version: '3.8'

services:
  tomcat:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blog
      SPRING_DATASOURCE_USERANME: root
      SPRING_DATASOURCE_PASSWORD: root

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"